version: '3.8'
services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-volume:/var/lib/pgql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
  fastapi:
    container_name: bookstore-api
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
     - "8000:8000"

volumes:
  postgres-volume: